### ISSUE TITLE
cdsw aws script causes null pointer exception

### ISSUE THREAD

**Issue by Data-drone** [cloudera/director-scripts#47]
I am trying to run the aws.cdsw.conf script after entering in all the details needed (REPLACE-ME) bits and I get a java.lang.NullPointerEception from the cloudera director (2.7)

relevant logs are:

`[2018-11-04 05:26:40.772 +0000] INFO  [main] - c.c.l.b.v.GenericClusterTemplateValidator: Validating parcel URL and version compatibility
[2018-11-04 05:26:40.926 +0000] ERROR [main] - com.cloudera.launchpad.Application: Command execution failed
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.cloudera.launchpad.parcel.ParcelInfoExtractor.getParcelInfo(ParcelInfoExtractor.java:175)
	at com.cloudera.launchpad.bootstrap.ClouderaManagerParcelValidations.validateParcelVersions(ClouderaManagerParcelValidations.java:89)
	at com.cloudera.launchpad.bootstrap.validators.GenericClusterTemplateValidator.validateParcelRepositories(GenericClusterTemplateValidator.java:172)
	at com.cloudera.launchpad.bootstrap.validators.GenericClusterTemplateValidator.validate(GenericClusterTemplateValidator.java:188)
	at com.cloudera.launchpad.model.ValidatorRegistry.validate(ValidatorRegistry.java:163)
	at com.cloudera.launchpad.commands.ValidateCommand.validate(ValidateCommand.java:221)
	at com.cloudera.launchpad.commands.BootstrapRemoteCommand.run(BootstrapRemoteCommand.java:142)
	at com.cloudera.launchpad.commands.RemoteCommand.run(RemoteCommand.java:204)
	at com.cloudera.launchpad.Application.run(Application.java:168)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:772)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at com.cloudera.launchpad.Application.start(Application.java:115)
	at com.cloudera.launchpad.Application.main(Application.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException: null
	at com.cloudera.launchpad.parcel.ParcelInfoExtractor.getParcelInfoFromManifest(ParcelInfoExtractor.java:184)
	at com.cloudera.launchpad.parcel.ParcelInfoExtractor$ParcelInfoCacheLoader.load(ParcelInfoExtractor.java:126)
	at com.cloudera.launchpad.parcel.ParcelInfoExtractor$ParcelInfoCacheLoader.load(ParcelInfoExtractor.java:104)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	... 26 common frames omitted
[2018-11-04 05:26:41.779 +0000] INFO  [Thread-10] - o.s.c.a.AnnotationConfigApplicationContext: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@b1a58a3: startup date [Sun Nov 04 05:26:17 UTC 2018]; root of context hierarchy
[2018-11-04 05:26:41.804 +0000] INFO  [Thread-10] - o.s.o.j.LocalContainerEntityManagerFactoryBean: Closing JPA EntityManagerFactory for persistence unit 'default'
[2018-11-04 05:26:41.811 +0000] WARN  [Thread-10] - c.c.l.c.security.CipherSchemeFactory: Allowing cipher scheme to be set again, prior scheme is com.cloudera.launchpad.common.security.TripleDESCipher@1fcb4808
`

**Comment by hallihan** [comment]
We had some mis-matched versions in the sample config previously. I just pushed an update this morning with versions that should work together.  Can you check out the latest and see if you still get an error?

**Comment by Data-drone** [comment]
yup works now thanks!
